### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mediocre9** [mediocre9/khaata#1]
# KHAATA APP

## Task-List
- [ ] **Bloc Pattern Implementation** 
- [ ] Code Refactoring
- [ ] Bug Hunting
- [ ] Profiling and Optimization
- [ ] Doxygen comment documentation
